### PR TITLE
Enh/feedback form

### PR DESCRIPTION
**Pull request by beaucronin**
- Add a simple email feedback form using barometer
- Add logging handler, including for email (doesn't work yet)

### CODE REVIEW

**Comment by okdistribute** [comment]
Are we ready to merge this?

**Comment by beaucronin** [comment]
Yes, seems to work. I can add the error reporting through sentry soon.

**Comment by beaucronin** [comment]
But that can be on a different branch.

**Comment by okdistribute** [comment]
awesome

**Pull request merged**
